[package]
name = "storage"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
chrono.workspace = true
core-domain = { path = "../core-domain" }
serde_json.workspace = true
shared-types = { path = "../shared-types" }
sqlx.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
tokio.workspace = true
