[package]
name = "auth"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
axum.workspace = true
core-domain = { path = "../core-domain" }
jsonwebtoken.workspace = true
reqwest.workspace = true
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true
