[package]
name = "progression"
edition.workspace = true
version.workspace = true
publish.workspace = true

[dependencies]
core-domain = { path = "../core-domain" }
shared-types = { path = "../shared-types" }
storage = { path = "../storage" }

[dev-dependencies]
chrono.workspace = true
tokio.workspace = true
uuid.workspace = true
