-- Fixed acceptance matrix for the four explicitly declared equipment inventories.
-- A required cell always needs >=3 distinct variants (>=2 after excluding source).
-- Unsupported cells must have zero physically available variants; the regression
-- rejects using an unsupported label to conceal a one- or two-variant shortage.
begin;
insert into public.exercise_replacement_profiles(slug,equipment_inventory,description) values
('home_bodyweight','["bodyweight", "chair", "wall", "table", "doorway", "stable_counter"]'::jsonb,'Household supports only; no assumed resistance gear.'),
('home_band','["bodyweight", "chair", "wall", "table", "doorway", "stable_counter", "band", "anchor", "high_anchor"]'::jsonb,'Household supports, bands and secure general/overhead anchors.'),
('home_dumbbell','["bodyweight", "chair", "wall", "table", "doorway", "stable_counter", "dumbbell", "bench", "step"]'::jsonb,'Household supports, dumbbells, a fixed exercise bench and step.'),
('gym','["bodyweight", "chair", "wall", "table", "doorway", "stable_counter", "band", "anchor", "high_anchor", "dumbbell", "bench", "adjustable_bench", "preacher_bench", "step", "barbell", "rack", "cable", "machine", "kettlebell", "fat_grip", "smith_machine", "plate", "rope", "rope_attachment", "cuff_attachment", "landmine", "ankle_weight", "sliders", "sliding_surface", "pull_up_bar", "neutral_grip_pull_up_bar", "dip_bars", "battle_ropes", "bike", "bicycle", "elliptical", "jump_rope", "stair_climber", "stairs", "treadmill", "pool", "foam_roller", "lacrosse_ball", "glute_ham_developer", "nordic_bench", "stick", "ab_crunch_machine", "assisted_dip_machine", "assisted_pull_up_machine", "belt_squat_machine", "chest_press_machine", "donkey_calf_machine", "hack_squat_machine", "hip_abduction_machine", "hip_adduction_machine", "hip_thrust_machine", "lat_pulldown_machine", "lateral_raise_machine", "leg_extension_machine", "leg_press_machine", "lying_leg_curl_machine", "pec_deck_machine", "pullover_machine", "row_machine", "seated_calf_machine", "seated_leg_curl_machine", "shoulder_press_machine", "shrug_machine", "standing_calf_machine", "t_bar_row_machine"]'::jsonb,'Explicit full gym inventory; generic machine does not grant all machines.')
on conflict(slug) do update set equipment_inventory=excluded.equipment_inventory,description=excluded.description;

insert into public.exercise_replacement_coverage_requirements(category,replacement_family,profile_slug,expectation,minimum_variant_groups,reason) values
('balance','single_leg_balance','home_bodyweight','required',3,null),
('balance','single_leg_balance','home_band','required',3,null),
('balance','single_leg_balance','home_dumbbell','required',3,null),
('balance','single_leg_balance','gym','required',3,null),
('balance','walking_balance','home_bodyweight','required',3,null),
('balance','walking_balance','home_band','required',3,null),
('balance','walking_balance','home_dumbbell','required',3,null),
('balance','walking_balance','gym','required',3,null),
('cardio','aerobic_activity','home_bodyweight','required',3,null),
('cardio','aerobic_activity','home_band','required',3,null),
('cardio','aerobic_activity','home_dumbbell','required',3,null),
('cardio','aerobic_activity','gym','required',3,null),
('mobility','shoulder_mobility','home_bodyweight','required',3,null),
('mobility','shoulder_mobility','home_band','required',3,null),
('mobility','shoulder_mobility','home_dumbbell','required',3,null),
('mobility','shoulder_mobility','gym','required',3,null),
('mobility','hip_rotation_mobility','home_bodyweight','required',3,null),
('mobility','hip_rotation_mobility','home_band','required',3,null),
('mobility','hip_rotation_mobility','home_dumbbell','required',3,null),
('mobility','hip_rotation_mobility','gym','required',3,null),
('mobility','thoracic_mobility','home_bodyweight','required',3,null),
('mobility','thoracic_mobility','home_band','required',3,null),
('mobility','thoracic_mobility','home_dumbbell','required',3,null),
('mobility','thoracic_mobility','gym','required',3,null),
('pilates','anti_extension','home_bodyweight','required',3,null),
('pilates','anti_extension','home_band','required',3,null),
('pilates','anti_extension','home_dumbbell','required',3,null),
('pilates','anti_extension','gym','required',3,null),
('pilates','anti_rotation','home_bodyweight','required',3,null),
('pilates','anti_rotation','home_band','required',3,null),
('pilates','anti_rotation','home_dumbbell','required',3,null),
('pilates','anti_rotation','gym','required',3,null),
('pilates','hip_abduction','home_bodyweight','required',3,null),
('pilates','hip_abduction','home_band','required',3,null),
('pilates','hip_abduction','home_dumbbell','required',3,null),
('pilates','hip_abduction','gym','required',3,null),
('pilates','hip_bridge','home_bodyweight','required',3,null),
('pilates','hip_bridge','home_band','required',3,null),
('pilates','hip_bridge','home_dumbbell','required',3,null),
('pilates','hip_bridge','gym','required',3,null),
('pilates','hip_external_rotation','home_bodyweight','required',3,null),
('pilates','hip_external_rotation','home_band','required',3,null),
('pilates','hip_external_rotation','home_dumbbell','required',3,null),
('pilates','hip_external_rotation','gym','required',3,null),
('pilates','pelvic_control','home_bodyweight','required',3,null),
('pilates','pelvic_control','home_band','required',3,null),
('pilates','pelvic_control','home_dumbbell','required',3,null),
('pilates','pelvic_control','gym','required',3,null),
('pilates','trunk_flexion','home_bodyweight','required',3,null),
('pilates','trunk_flexion','home_band','required',3,null),
('pilates','trunk_flexion','home_dumbbell','required',3,null),
('pilates','trunk_flexion','gym','required',3,null),
('stretching','calf_stretch_bent_knee','home_bodyweight','required',3,null),
('stretching','calf_stretch_bent_knee','home_band','required',3,null),
('stretching','calf_stretch_bent_knee','home_dumbbell','required',3,null),
('stretching','calf_stretch_bent_knee','gym','required',3,null),
('stretching','calf_stretch_straight_knee','home_bodyweight','required',3,null),
('stretching','calf_stretch_straight_knee','home_band','required',3,null),
('stretching','calf_stretch_straight_knee','home_dumbbell','required',3,null),
('stretching','calf_stretch_straight_knee','gym','required',3,null),
('stretching','chest_stretch','home_bodyweight','required',3,null),
('stretching','chest_stretch','home_band','required',3,null),
('stretching','chest_stretch','home_dumbbell','required',3,null),
('stretching','chest_stretch','gym','required',3,null),
('stretching','glute_stretch','home_bodyweight','required',3,null),
('stretching','glute_stretch','home_band','required',3,null),
('stretching','glute_stretch','home_dumbbell','required',3,null),
('stretching','glute_stretch','gym','required',3,null),
('stretching','hamstring_stretch','home_bodyweight','required',3,null),
('stretching','hamstring_stretch','home_band','required',3,null),
('stretching','hamstring_stretch','home_dumbbell','required',3,null),
('stretching','hamstring_stretch','gym','required',3,null),
('stretching','hip_flexor_stretch','home_bodyweight','required',3,null),
('stretching','hip_flexor_stretch','home_band','required',3,null),
('stretching','hip_flexor_stretch','home_dumbbell','required',3,null),
('stretching','hip_flexor_stretch','gym','required',3,null),
('stretching','hip_rotation_stretch','home_bodyweight','required',3,null),
('stretching','hip_rotation_stretch','home_band','required',3,null),
('stretching','hip_rotation_stretch','home_dumbbell','required',3,null),
('stretching','hip_rotation_stretch','gym','required',3,null),
('stretching','outer_hip_stretch','home_bodyweight','required',3,null),
('stretching','outer_hip_stretch','home_band','required',3,null),
('stretching','outer_hip_stretch','home_dumbbell','required',3,null),
('stretching','outer_hip_stretch','gym','required',3,null),
('stretching','posterior_shoulder_stretch','home_bodyweight','required',3,null),
('stretching','posterior_shoulder_stretch','home_band','required',3,null),
('stretching','posterior_shoulder_stretch','home_dumbbell','required',3,null),
('stretching','posterior_shoulder_stretch','gym','required',3,null),
('stretching','quadriceps_stretch','home_bodyweight','required',3,null),
('stretching','quadriceps_stretch','home_band','required',3,null),
('stretching','quadriceps_stretch','home_dumbbell','required',3,null),
('stretching','quadriceps_stretch','gym','required',3,null),
('stretching','shoulder_external_rotation_stretch','home_bodyweight','required',3,null),
('stretching','shoulder_external_rotation_stretch','home_band','required',3,null),
('stretching','shoulder_external_rotation_stretch','home_dumbbell','required',3,null),
('stretching','shoulder_external_rotation_stretch','gym','required',3,null),
('stretching','wrist_extensor_stretch','home_bodyweight','required',3,null),
('stretching','wrist_extensor_stretch','home_band','required',3,null),
('stretching','wrist_extensor_stretch','home_dumbbell','required',3,null),
('stretching','wrist_extensor_stretch','gym','required',3,null),
('stretching','wrist_flexor_stretch','home_bodyweight','required',3,null),
('stretching','wrist_flexor_stretch','home_band','required',3,null),
('stretching','wrist_flexor_stretch','home_dumbbell','required',3,null),
('stretching','wrist_flexor_stretch','gym','required',3,null),
('recovery','glute_soft_tissue','home_bodyweight','unsupported_equipment',null,'This tool-assisted self-massage family requires a foam roller or lacrosse ball; this inventory contains neither.'),
('recovery','glute_soft_tissue','home_band','unsupported_equipment',null,'This tool-assisted self-massage family requires a foam roller or lacrosse ball; this inventory contains neither.'),
('recovery','glute_soft_tissue','home_dumbbell','unsupported_equipment',null,'This tool-assisted self-massage family requires a foam roller or lacrosse ball; this inventory contains neither.'),
('recovery','glute_soft_tissue','gym','required',3,null),
('strength','ankle_dorsiflexion','home_bodyweight','required',3,null),
('strength','ankle_dorsiflexion','home_band','required',3,null),
('strength','ankle_dorsiflexion','home_dumbbell','required',3,null),
('strength','ankle_dorsiflexion','gym','required',3,null),
('strength','anti_extension','home_bodyweight','required',3,null),
('strength','anti_extension','home_band','required',3,null),
('strength','anti_extension','home_dumbbell','required',3,null),
('strength','anti_extension','gym','required',3,null),
('strength','anti_lateral_flexion','home_bodyweight','required',3,null),
('strength','anti_lateral_flexion','home_band','required',3,null),
('strength','anti_lateral_flexion','home_dumbbell','required',3,null),
('strength','anti_lateral_flexion','gym','required',3,null),
('strength','anti_rotation','home_bodyweight','required',3,null),
('strength','anti_rotation','home_band','required',3,null),
('strength','anti_rotation','home_dumbbell','required',3,null),
('strength','anti_rotation','gym','required',3,null),
('strength','calf_raise_bent_knee','home_bodyweight','required',3,null),
('strength','calf_raise_bent_knee','home_band','required',3,null),
('strength','calf_raise_bent_knee','home_dumbbell','required',3,null),
('strength','calf_raise_bent_knee','gym','required',3,null),
('strength','calf_raise_straight_knee','home_bodyweight','required',3,null),
('strength','calf_raise_straight_knee','home_band','required',3,null),
('strength','calf_raise_straight_knee','home_dumbbell','required',3,null),
('strength','calf_raise_straight_knee','gym','required',3,null),
('strength','hip_abduction','home_bodyweight','required',3,null),
('strength','hip_abduction','home_band','required',3,null),
('strength','hip_abduction','home_dumbbell','required',3,null),
('strength','hip_abduction','gym','required',3,null),
('strength','hip_adduction','home_bodyweight','required',3,null),
('strength','hip_adduction','home_band','required',3,null),
('strength','hip_adduction','home_dumbbell','required',3,null),
('strength','hip_adduction','gym','required',3,null),
('strength','hip_bridge','home_bodyweight','required',3,null),
('strength','hip_bridge','home_band','required',3,null),
('strength','hip_bridge','home_dumbbell','required',3,null),
('strength','hip_bridge','gym','required',3,null),
('strength','hip_hinge','home_bodyweight','required',3,null),
('strength','hip_hinge','home_band','required',3,null),
('strength','hip_hinge','home_dumbbell','required',3,null),
('strength','hip_hinge','gym','required',3,null),
('strength','knee_extension','home_bodyweight','required',3,null),
('strength','knee_extension','home_band','required',3,null),
('strength','knee_extension','home_dumbbell','required',3,null),
('strength','knee_extension','gym','required',3,null),
('strength','knee_flexion','home_bodyweight','required',3,null),
('strength','knee_flexion','home_band','required',3,null),
('strength','knee_flexion','home_dumbbell','required',3,null),
('strength','knee_flexion','gym','required',3,null),
('strength','lunge_split_squat','home_bodyweight','required',3,null),
('strength','lunge_split_squat','home_band','required',3,null),
('strength','lunge_split_squat','home_dumbbell','required',3,null),
('strength','lunge_split_squat','gym','required',3,null),
('strength','squat','home_bodyweight','required',3,null),
('strength','squat','home_band','required',3,null),
('strength','squat','home_dumbbell','required',3,null),
('strength','squat','gym','required',3,null),
('strength','hip_external_rotation','home_bodyweight','required',3,null),
('strength','hip_external_rotation','home_band','required',3,null),
('strength','hip_external_rotation','home_dumbbell','required',3,null),
('strength','hip_external_rotation','gym','required',3,null),
('strength','calf_plyometric','home_bodyweight','required',3,null),
('strength','calf_plyometric','home_band','required',3,null),
('strength','calf_plyometric','home_dumbbell','required',3,null),
('strength','calf_plyometric','gym','required',3,null),
('strength','horizontal_press','home_bodyweight','required',3,null),
('strength','horizontal_press','home_band','required',3,null),
('strength','horizontal_press','home_dumbbell','required',3,null),
('strength','horizontal_press','gym','required',3,null),
('strength','trunk_flexion','home_bodyweight','required',3,null),
('strength','trunk_flexion','home_band','required',3,null),
('strength','trunk_flexion','home_dumbbell','required',3,null),
('strength','trunk_flexion','gym','required',3,null),
('strength','scapular_upward_rotation','home_bodyweight','required',3,null),
('strength','scapular_upward_rotation','home_band','required',3,null),
('strength','scapular_upward_rotation','home_dumbbell','required',3,null),
('strength','scapular_upward_rotation','gym','required',3,null),
('strength','step_up','home_bodyweight','unsupported_equipment',null,'Step-up variants require a purpose-suitable step or platform; a household chair/table is not assumed to be a step.'),
('strength','step_up','home_band','unsupported_equipment',null,'Step-up variants require a purpose-suitable step or platform; a household chair/table is not assumed to be a step.'),
('strength','step_up','home_dumbbell','required',3,null),
('strength','step_up','gym','required',3,null),
('strength','hanging_leg_raise','home_bodyweight','unsupported_equipment',null,'Hanging variants require a load-rated pull-up bar; a doorway alone is not a bar.'),
('strength','hanging_leg_raise','home_band','unsupported_equipment',null,'Hanging variants require a load-rated pull-up bar; a doorway alone is not a bar.'),
('strength','hanging_leg_raise','home_dumbbell','unsupported_equipment',null,'Hanging variants require a load-rated pull-up bar; a doorway alone is not a bar.'),
('strength','hanging_leg_raise','gym','required',3,null),
('strength','chest_fly','home_bodyweight','unsupported_equipment',null,'The curated fly variants require dumbbells with appropriate support or a cable/pec-deck machine; this inventory has none of those setups.'),
('strength','chest_fly','home_band','unsupported_equipment',null,'The curated fly variants require dumbbells with appropriate support or a cable/pec-deck machine; this inventory has none of those setups.'),
('strength','chest_fly','home_dumbbell','required',3,null),
('strength','chest_fly','gym','required',3,null),
('strength','dip','home_bodyweight','unsupported_equipment',null,'The curated dip variants require a stable exercise bench, dip bars or an assisted-dip machine; ordinary chairs/counters are not assumed to be rated dip supports.'),
('strength','dip','home_band','unsupported_equipment',null,'The curated dip variants require a stable exercise bench, dip bars or an assisted-dip machine; ordinary chairs/counters are not assumed to be rated dip supports.'),
('strength','dip','home_dumbbell','required',3,null),
('strength','dip','gym','required',3,null),
('strength','elbow_extension','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','elbow_extension','home_band','required',3,null),
('strength','elbow_extension','home_dumbbell','required',3,null),
('strength','elbow_extension','gym','required',3,null),
('strength','elbow_flexion','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','elbow_flexion','home_band','required',3,null),
('strength','elbow_flexion','home_dumbbell','required',3,null),
('strength','elbow_flexion','gym','required',3,null),
('strength','horizontal_row','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','horizontal_row','home_band','required',3,null),
('strength','horizontal_row','home_dumbbell','required',3,null),
('strength','horizontal_row','gym','required',3,null),
('strength','lateral_raise','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','lateral_raise','home_band','required',3,null),
('strength','lateral_raise','home_dumbbell','required',3,null),
('strength','lateral_raise','gym','required',3,null),
('strength','shoulder_external_rotation','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','shoulder_external_rotation','home_band','required',3,null),
('strength','shoulder_external_rotation','home_dumbbell','required',3,null),
('strength','shoulder_external_rotation','gym','required',3,null),
('strength','shoulder_internal_rotation','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','shoulder_internal_rotation','home_band','required',3,null),
('strength','shoulder_internal_rotation','home_dumbbell','required',3,null),
('strength','shoulder_internal_rotation','gym','required',3,null),
('strength','vertical_press','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','vertical_press','home_band','required',3,null),
('strength','vertical_press','home_dumbbell','required',3,null),
('strength','vertical_press','gym','required',3,null),
('strength','wrist_extension','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','wrist_extension','home_band','required',3,null),
('strength','wrist_extension','home_dumbbell','required',3,null),
('strength','wrist_extension','gym','required',3,null),
('strength','wrist_flexion','home_bodyweight','unsupported_equipment',null,'The curated variants require resistance bands, dumbbells or gym equipment; this inventory lacks the required resistance implement.'),
('strength','wrist_flexion','home_band','required',3,null),
('strength','wrist_flexion','home_dumbbell','required',3,null),
('strength','wrist_flexion','gym','required',3,null),
('strength','rear_delt_fly','home_bodyweight','unsupported_equipment',null,'The curated variants require dumbbells or a specific gym loading setup; this inventory lacks those implements.'),
('strength','rear_delt_fly','home_band','unsupported_equipment',null,'The curated variants require dumbbells or a specific gym loading setup; this inventory lacks those implements.'),
('strength','rear_delt_fly','home_dumbbell','required',3,null),
('strength','rear_delt_fly','gym','required',3,null),
('strength','scapular_elevation','home_bodyweight','unsupported_equipment',null,'The curated variants require dumbbells or a specific gym loading setup; this inventory lacks those implements.'),
('strength','scapular_elevation','home_band','unsupported_equipment',null,'The curated variants require dumbbells or a specific gym loading setup; this inventory lacks those implements.'),
('strength','scapular_elevation','home_dumbbell','required',3,null),
('strength','scapular_elevation','gym','required',3,null),
('strength','upright_row','home_bodyweight','unsupported_equipment',null,'The curated variants require dumbbells or a specific gym loading setup; this inventory lacks those implements.'),
('strength','upright_row','home_band','unsupported_equipment',null,'The curated variants require dumbbells or a specific gym loading setup; this inventory lacks those implements.'),
('strength','upright_row','home_dumbbell','required',3,null),
('strength','upright_row','gym','required',3,null),
('strength','face_pull','home_bodyweight','unsupported_equipment',null,'The curated face-pull variants require an adjustable cable and rope attachment; this inventory lacks the cable setup.'),
('strength','face_pull','home_band','unsupported_equipment',null,'The curated face-pull variants require an adjustable cable and rope attachment; this inventory lacks the cable setup.'),
('strength','face_pull','home_dumbbell','unsupported_equipment',null,'The curated face-pull variants require an adjustable cable and rope attachment; this inventory lacks the cable setup.'),
('strength','face_pull','gym','required',3,null),
('strength','scapular_retraction','home_bodyweight','unsupported_equipment',null,'The curated loaded retraction variants require a chest-supported incline/row station or cable setup; a fixed bench alone is not that setup.'),
('strength','scapular_retraction','home_band','unsupported_equipment',null,'The curated loaded retraction variants require a chest-supported incline/row station or cable setup; a fixed bench alone is not that setup.'),
('strength','scapular_retraction','home_dumbbell','unsupported_equipment',null,'The curated loaded retraction variants require a chest-supported incline/row station or cable setup; a fixed bench alone is not that setup.'),
('strength','scapular_retraction','gym','required',3,null),
('strength','shoulder_extension','home_bodyweight','unsupported_equipment',null,'The curated pullover/straight-arm extension variants require gym loading equipment (barbell, cable or pullover machine).'),
('strength','shoulder_extension','home_band','unsupported_equipment',null,'The curated pullover/straight-arm extension variants require gym loading equipment (barbell, cable or pullover machine).'),
('strength','shoulder_extension','home_dumbbell','unsupported_equipment',null,'The curated pullover/straight-arm extension variants require gym loading equipment (barbell, cable or pullover machine).'),
('strength','shoulder_extension','gym','required',3,null),
('strength','vertical_pull','home_bodyweight','unsupported_equipment',null,'Vertical pulling variants require a secure overhead band anchor, pull-up bar or pulldown station; this inventory has none.'),
('strength','vertical_pull','home_band','required',3,null),
('strength','vertical_pull','home_dumbbell','unsupported_equipment',null,'Vertical pulling variants require a secure overhead band anchor, pull-up bar or pulldown station; this inventory has none.'),
('strength','vertical_pull','gym','required',3,null)
on conflict(category,replacement_family,profile_slug) do update set
 expectation=excluded.expectation,minimum_variant_groups=excluded.minimum_variant_groups,reason=excluded.reason;

-- Candidate selection and conservative alias-anatomy exclusions share this path.
create index if not exists exercises_eligible_family_variant_idx
 on public.exercises(category,replacement_family,(coalesce(variant_group,slug)))
 where is_active and replacement_status='eligible';
commit;
